import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import InitPage from "./InitPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Easiest CV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " custom-body"}>{children}</body>
    </html>
  );
}
